name: Unit & Integration Tests

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup JDK 1.9
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Unit & Integration Tests
        run: mvn verify -f rup-projects-core/

      - name: run spring context
        run: cd rup-projects-core && mvn package && java -jar target/rup-projects-core-0.0.1-SNAPSHOT.jar &

      - name: move to web app
        run: ls

      - name: move to web app
        run: cd web-app && ls

      - name: Cypress run

        uses: cypress-io/github-action@v2
        with:
          build: npm run build
          start: npm start


